//! OSPF Interoperability and Conformance Tests.
//!
//! Test structure modeled on the UNH IOL OSPF Interoperability Test Suite
//! (https://www.iol.unh.edu/sites/default/files/testsuites/routing/OSPF_Interop.pdf).
//!
//! Each test has:
//! - **Purpose**: What the test verifies
//! - **References**: The RFC section being tested
//! - **Procedure**: Steps executed
//! - **Expected**: What should happen
//!
//! Phase 1 coverage is limited to single-area OSPFv2 functionality.
//! Tests that require multi-area, stub areas, authentication, or AS-externals
//! are marked `#[ignore]` and deferred to Phase 2.

use std::net::Ipv4Addr;

use std::collections::HashMap;

use ospfd::packet::*;
use ospfd::packet::hello::{HelloPacket, OspfOptions};
use ospfd::packet::lsa::*;
use ospfd::proto::interface::*;
use ospfd::proto::neighbor::*;
use ospfd::proto::spf::{
    calculate_external_routes, calculate_inter_area_routes, calculate_spf,
    calculate_spf_with_paths, SpfInterface, SpfNeighbor,
};

// ============================================================================
// Group 1: Packet Format Conformance
// ============================================================================
// These tests validate that our packet layer produces and parses byte streams
// compatible with the OSPFv2 wire format (RFC 2328 Appendix A).

/// Test FMT.1: Parse a real FRR Hello packet
///
/// Purpose: Verify the parser correctly handles a Hello packet generated by
/// FRR 10.x in a production setting. Every field must parse to its expected
/// value and re-encoding must produce byte-identical output.
///
/// References: RFC 2328 Sections A.3.1, A.3.2
#[test]
fn fmt_1_parse_real_frr_hello() {
    // Captured from FRR 10.x running on Debian Bookworm, router-id 172.30.0.1,
    // sending to 224.0.0.5 on the WAN interface of an test environment.
    // IP header stripped; data starts at the OSPF header.
    let ospf_data: [u8; 48] = [
        0x02, 0x01, 0x00, 0x30, 0xac, 0x1e, 0x00, 0x01,
        0x00, 0x00, 0x00, 0x00, 0x4c, 0x1a, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0xff, 0xff, 0xff, 0x00, 0x00, 0x0a, 0x02, 0x01,
        0x00, 0x00, 0x00, 0x28, 0xac, 0x1e, 0x00, 0x01,
        0xac, 0x1e, 0x00, 0x02, 0xac, 0x1e, 0x00, 0x02,
    ];

    // Step 1: Verify the OSPF checksum
    assert!(
        verify_ospf_checksum(&ospf_data),
        "FRR Hello checksum did not validate"
    );

    // Step 2: Parse the packet
    let packet = OspfPacket::parse(&ospf_data).expect("parse FRR Hello");

    match packet {
        OspfPacket::Hello(header, hello) => {
            // Step 3: Verify header fields
            assert_eq!(header.version, 2, "OSPF version");
            assert_eq!(header.packet_length, 48, "packet length");
            assert_eq!(header.router_id, Ipv4Addr::new(172, 30, 0, 1));
            assert_eq!(header.area_id, Ipv4Addr::UNSPECIFIED, "area 0");
            assert_eq!(header.au_type, 0, "no authentication");

            // Step 4: Verify Hello body fields
            assert_eq!(hello.network_mask, Ipv4Addr::new(255, 255, 255, 0));
            assert_eq!(hello.hello_interval, 10);
            assert_eq!(hello.options.0, 0x02, "E bit set");
            assert_eq!(hello.router_priority, 1);
            assert_eq!(hello.router_dead_interval, 40);
            assert_eq!(hello.designated_router, Ipv4Addr::new(172, 30, 0, 1));
            assert_eq!(hello.backup_designated_router, Ipv4Addr::new(172, 30, 0, 2));
            assert_eq!(hello.neighbors.len(), 1);
            assert_eq!(hello.neighbors[0], Ipv4Addr::new(172, 30, 0, 2));

            // Step 5: Re-encode and verify byte-for-byte match
            let reencoded = OspfPacket::Hello(header, hello).encode();
            assert_eq!(
                reencoded.as_slice(),
                &ospf_data[..],
                "re-encoded Hello does not match original"
            );
        }
        _ => panic!("expected Hello packet"),
    }
}

// ============================================================================
// Group 2: Neighbor State Machine (RFC 2328 Section 10.3)
// ============================================================================

/// Test NSM.1: Normal adjacency formation on broadcast network.
///
/// Purpose: Verify that a neighbor progresses from Down to Full through the
/// standard state sequence when forming adjacency on a broadcast network.
///
/// References: RFC 2328 Section 10.3
///
/// Procedure:
///   1. Create a neighbor in Down state
///   2. Send HelloReceived -> expect Init
///   3. Send TwoWayReceived with adjacency -> expect ExStart
///   4. Send NegotiationDone -> expect Exchange
///   5. With empty request list, send ExchangeDone -> expect Full
#[test]
fn nsm_1_full_adjacency_formation() {
    let mut n = Neighbor::new(
        Ipv4Addr::new(2, 2, 2, 2),
        Ipv4Addr::new(10, 0, 0, 2),
    );
    assert_eq!(n.state, NeighborState::Down);

    assert_eq!(
        n.handle_event(&NeighborEvent::HelloReceived, false),
        Some(NeighborState::Init)
    );
    assert_eq!(
        n.handle_event(&NeighborEvent::TwoWayReceived, true),
        Some(NeighborState::ExStart)
    );
    assert_eq!(
        n.handle_event(&NeighborEvent::NegotiationDone, true),
        Some(NeighborState::Exchange)
    );
    assert_eq!(
        n.handle_event(&NeighborEvent::ExchangeDone, true),
        Some(NeighborState::Full)
    );
}

/// Test NSM.2: DR-Other neighbors stay in 2-Way.
///
/// Purpose: Verify that on a broadcast network, neighbors that are neither
/// DR nor BDR do not form full adjacencies — they stop at 2-Way.
///
/// References: RFC 2328 Section 10.3 (event 2-WayReceived)
#[test]
fn nsm_2_dr_other_stops_at_twoway() {
    let mut n = Neighbor::new(
        Ipv4Addr::new(3, 3, 3, 3),
        Ipv4Addr::new(10, 0, 0, 3),
    );
    n.handle_event(&NeighborEvent::HelloReceived, false);
    // Neither we nor the neighbor is DR/BDR
    n.handle_event(&NeighborEvent::TwoWayReceived, false);
    assert_eq!(n.state, NeighborState::TwoWay);
}

/// Test NSM.3: Sequence number mismatch restarts DD exchange.
///
/// Purpose: Verify that a SeqNumberMismatch event in Exchange or later
/// transitions the neighbor back to ExStart, clearing exchange state.
///
/// References: RFC 2328 Section 10.3 (event SeqNumberMismatch)
#[test]
fn nsm_3_seq_mismatch_restarts_dd() {
    let mut n = Neighbor::new(
        Ipv4Addr::new(2, 2, 2, 2),
        Ipv4Addr::new(10, 0, 0, 2),
    );
    n.handle_event(&NeighborEvent::HelloReceived, false);
    n.handle_event(&NeighborEvent::TwoWayReceived, true);
    n.handle_event(&NeighborEvent::NegotiationDone, true);
    assert_eq!(n.state, NeighborState::Exchange);

    // Simulate a mismatch
    n.handle_event(&NeighborEvent::SeqNumberMismatch, true);
    assert_eq!(n.state, NeighborState::ExStart);
}

/// Test NSM.4: Inactivity timer kills neighbor.
///
/// Purpose: Verify that when the RouterDeadInterval elapses without a Hello,
/// the neighbor transitions to Down from any state.
///
/// References: RFC 2328 Section 10.3 (event InactivityTimer)
#[test]
fn nsm_4_inactivity_timer_resets() {
    let mut n = Neighbor::new(
        Ipv4Addr::new(2, 2, 2, 2),
        Ipv4Addr::new(10, 0, 0, 2),
    );
    n.handle_event(&NeighborEvent::HelloReceived, false);
    n.handle_event(&NeighborEvent::TwoWayReceived, true);
    n.handle_event(&NeighborEvent::NegotiationDone, true);
    n.handle_event(&NeighborEvent::ExchangeDone, true);
    assert_eq!(n.state, NeighborState::Full);

    n.handle_event(&NeighborEvent::InactivityTimer, false);
    assert_eq!(n.state, NeighborState::Down);
    assert!(n.ls_request_list.is_empty());
    assert!(n.ls_retransmit_list.is_empty());
}

// ============================================================================
// Group 3: Interface State Machine (RFC 2328 Section 9.3)
// ============================================================================

/// Test ISM.1: Single router on broadcast network becomes DR.
///
/// Purpose: Verify that when a router is alone on a broadcast network and
/// its WaitTimer expires, it elects itself as DR.
///
/// References: RFC 2328 Section 9.4 (DR Election Algorithm)
///
/// Derived from: UNH IOL OSPF_Interop.1.4 (Event Backup Seen)
#[test]
fn ism_1_alone_router_becomes_dr() {
    let mut iface = OspfInterface::new(
        "wan".to_string(),
        1,
        Ipv4Addr::new(10, 0, 0, 1),
        Ipv4Addr::new(255, 255, 255, 0),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::Broadcast,
        Ipv4Addr::new(10, 0, 0, 1),
    );
    iface.priority = 1;

    // InterfaceUp -> Waiting
    iface.handle_event(&InterfaceEvent::InterfaceUp);
    assert_eq!(iface.state, InterfaceState::Waiting);

    // WaitTimer -> DR election -> we're alone, we become DR
    iface.handle_event(&InterfaceEvent::WaitTimer);
    assert_eq!(iface.state, InterfaceState::DR);
    assert_eq!(iface.dr, Ipv4Addr::new(10, 0, 0, 1));
}

/// Test ISM.2: Point-to-Point interface skips DR election.
///
/// Purpose: Verify that P2P interfaces go directly to Point-to-Point state
/// on InterfaceUp without waiting for DR election.
///
/// References: RFC 2328 Section 9.3 (Interface state changes)
#[test]
fn ism_2_p2p_skips_election() {
    let mut iface = OspfInterface::new(
        "tun0".to_string(),
        1,
        Ipv4Addr::new(10, 255, 0, 1),
        Ipv4Addr::new(255, 255, 255, 252),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::PointToPoint,
        Ipv4Addr::new(10, 255, 0, 1),
    );
    iface.handle_event(&InterfaceEvent::InterfaceUp);
    assert_eq!(iface.state, InterfaceState::PointToPoint);
}

/// Test ISM.3: Zero-priority router never becomes DR.
///
/// Purpose: Verify that a router configured with priority 0 does not
/// participate in DR election — it goes directly to DROther on InterfaceUp.
///
/// References: RFC 2328 Section 9.3, 9.4
#[test]
fn ism_3_zero_priority_is_drother() {
    let mut iface = OspfInterface::new(
        "wan".to_string(),
        1,
        Ipv4Addr::new(10, 0, 0, 1),
        Ipv4Addr::new(255, 255, 255, 0),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::Broadcast,
        Ipv4Addr::new(10, 0, 0, 1),
    );
    iface.priority = 0;
    iface.handle_event(&InterfaceEvent::InterfaceUp);
    assert_eq!(iface.state, InterfaceState::DROther);
}

// ============================================================================
// Group 4: Hello Protocol (RFC 2328 Section 10.5)
// ============================================================================

/// Test HELLO.1: Hello packet roundtrip with multiple neighbors.
///
/// Purpose: Verify Hello packet encoding and parsing with realistic
/// neighbor list sizes.
#[test]
fn hello_1_multi_neighbor_roundtrip() {
    let hello = HelloPacket {
        network_mask: Ipv4Addr::new(255, 255, 255, 0),
        hello_interval: 10,
        options: OspfOptions::standard(),
        router_priority: 1,
        router_dead_interval: 40,
        designated_router: Ipv4Addr::new(10, 0, 0, 1),
        backup_designated_router: Ipv4Addr::new(10, 0, 0, 2),
        neighbors: vec![
            Ipv4Addr::new(1, 1, 1, 1),
            Ipv4Addr::new(2, 2, 2, 2),
            Ipv4Addr::new(3, 3, 3, 3),
            Ipv4Addr::new(4, 4, 4, 4),
            Ipv4Addr::new(5, 5, 5, 5),
        ],
    };

    let mut buf = Vec::new();
    hello.encode(&mut buf);
    let parsed = HelloPacket::parse(&buf).expect("parse");
    assert_eq!(parsed.neighbors.len(), 5);
    assert_eq!(parsed.neighbors[0], Ipv4Addr::new(1, 1, 1, 1));
    assert_eq!(parsed.neighbors[4], Ipv4Addr::new(5, 5, 5, 5));
}

// ============================================================================
// Group 5: LSA (RFC 2328 Section 12)
// ============================================================================

/// Test LSA.1: Router-LSA encoding with mixed link types.
///
/// Purpose: Verify Router-LSA generation with both point-to-point and stub
/// network links in a single LSA.
///
/// References: RFC 2328 Section 12.4.1
#[test]
fn lsa_1_router_lsa_mixed_links() {
    let lsa = RouterLsa {
        flags: RouterLsa::E_FLAG,
        links: vec![
            RouterLink {
                link_id: Ipv4Addr::new(2, 2, 2, 2),
                link_data: Ipv4Addr::new(10, 0, 0, 1),
                link_type: RouterLinkType::PointToPoint,
                num_tos: 0,
                metric: 10,
            },
            RouterLink {
                link_id: Ipv4Addr::new(10, 0, 0, 0),
                link_data: Ipv4Addr::new(255, 255, 255, 252),
                link_type: RouterLinkType::StubNetwork,
                num_tos: 0,
                metric: 10,
            },
        ],
    };

    let mut buf = Vec::new();
    lsa.encode(&mut buf);
    let parsed = RouterLsa::parse(&buf).expect("parse");
    assert_eq!(parsed.links.len(), 2);
    assert_eq!(parsed.links[0].link_type, RouterLinkType::PointToPoint);
    assert_eq!(parsed.links[1].link_type, RouterLinkType::StubNetwork);
}

// ============================================================================
// Group 6: Authentication (RFC 2328 Appendix D)
// ============================================================================

/// Test AUTH.1: Simple password authentication round-trip.
///
/// Purpose: Verify that an OSPF packet authenticated with a simple password
/// can be verified on receive with the same password, and fails with a
/// different password.
///
/// References: RFC 2328 Appendix D.3
///
/// Derived from: UNH IOL OSPF_Interop.1.2 (Authentication)
#[test]
fn auth_1_simple_password() {
    use ospfd::packet::auth::{apply_auth, verify_auth, AuthKey};

    // A minimal Hello packet (just the header, we don't care about body for
    // auth verification — the 24-byte header is enough).
    let mut packet = vec![0u8; 48];
    packet[0] = 2; // version
    packet[1] = 1; // hello
    packet[2] = 0;
    packet[3] = 48;

    let key = AuthKey::Simple(b"ospfpass".to_vec());
    let authed = apply_auth(packet, &key, 0);

    // Matching password passes
    assert!(verify_auth(&authed, &key));

    // Different password fails
    let wrong = AuthKey::Simple(b"wrongpw".to_vec());
    assert!(!verify_auth(&authed, &wrong));

    // Null auth fails (au_type mismatch)
    assert!(!verify_auth(&authed, &AuthKey::None));
}

/// Test AUTH.2: MD5 cryptographic authentication round-trip.
///
/// Purpose: Verify that an OSPF packet authenticated with MD5 HMAC-like
/// scheme (RFC 2328 Appendix D.4) can be verified with the correct key_id
/// and key, and fails if either is wrong.
#[test]
fn auth_2_md5_crypto() {
    use ospfd::packet::auth::{apply_auth, verify_auth, AuthKey};

    let mut packet = vec![0u8; 48];
    packet[0] = 2;
    packet[1] = 1;
    packet[2] = 0;
    packet[3] = 48;
    for i in 24..48 {
        packet[i] = i as u8;
    }

    let key = AuthKey::Md5 {
        key_id: 7,
        key: b"super-secret-key".to_vec(),
    };
    let authed = apply_auth(packet, &key, 12345);

    // Packet length in header does NOT include the 16-byte digest
    assert_eq!(u16::from_be_bytes([authed[2], authed[3]]), 48);
    // Total buffer IS extended
    assert_eq!(authed.len(), 48 + 16);

    assert!(verify_auth(&authed, &key));

    // Wrong key_id fails
    let wrong_kid = AuthKey::Md5 {
        key_id: 8,
        key: b"super-secret-key".to_vec(),
    };
    assert!(!verify_auth(&authed, &wrong_kid));

    // Wrong key fails
    let wrong_key = AuthKey::Md5 {
        key_id: 7,
        key: b"different-key".to_vec(),
    };
    assert!(!verify_auth(&authed, &wrong_key));
}

// ============================================================================
// Group 7: SPF and Route Computation (RFC 2328 Section 16)
// ============================================================================

/// Test SPF.1: Next-hop resolution through a transit broadcast network.
///
/// Purpose: Verify that when SPF reaches a remote router via a transit
/// broadcast network (Network-LSA), routes inherit the correct next-hop
/// (the remote router's interface IP on the network) and outgoing
/// interface (our local sw_if_index attached to the network).
///
/// References: RFC 2328 Sections 16.1, 16.1.1
///
/// This is the bug we hit in our first live FRR interop test: routes were
/// being installed with next_hop=0.0.0.0 / sw_if_index=0 because we weren't
/// resolving next-hops through Network-LSAs.
#[test]
fn spf_1_transit_network_next_hop() {
    let mut lsdb = HashMap::new();

    // Us (R1) on broadcast network 172.30.0.0/24, R2 (FRR-like) is DR
    let r1 = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Router,
            link_state_id: Ipv4Addr::new(172, 30, 0, 2),
            advertising_router: Ipv4Addr::new(172, 30, 0, 2),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36,
        },
        body: LsaBody::Router(RouterLsa {
            flags: 0,
            links: vec![RouterLink {
                link_id: Ipv4Addr::new(172, 30, 0, 1),  // DR's address
                link_data: Ipv4Addr::new(172, 30, 0, 2), // our address
                link_type: RouterLinkType::TransitNetwork,
                num_tos: 0,
                metric: 10,
            }],
        }),
    };
    lsdb.insert(r1.key(), r1);

    // R2 (DR, FRR-like) on the same network with a stub for an internal /32
    let r2 = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Router,
            link_state_id: Ipv4Addr::new(172, 30, 0, 1),
            advertising_router: Ipv4Addr::new(172, 30, 0, 1),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 48,
        },
        body: LsaBody::Router(RouterLsa {
            flags: 0,
            links: vec![
                RouterLink {
                    link_id: Ipv4Addr::new(172, 30, 0, 1),
                    link_data: Ipv4Addr::new(172, 30, 0, 1),
                    link_type: RouterLinkType::TransitNetwork,
                    num_tos: 0,
                    metric: 10,
                },
                RouterLink {
                    link_id: Ipv4Addr::new(10, 99, 0, 1),
                    link_data: Ipv4Addr::new(255, 255, 255, 255),
                    link_type: RouterLinkType::StubNetwork,
                    num_tos: 0,
                    metric: 0,
                },
            ],
        }),
    };
    lsdb.insert(r2.key(), r2);

    // Network-LSA for the transit network
    let net = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Network,
            link_state_id: Ipv4Addr::new(172, 30, 0, 1),
            advertising_router: Ipv4Addr::new(172, 30, 0, 1),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 32,
        },
        body: LsaBody::Network(NetworkLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            attached_routers: vec![
                Ipv4Addr::new(172, 30, 0, 2), // us
                Ipv4Addr::new(172, 30, 0, 1), // DR
            ],
        }),
    };
    lsdb.insert(net.key(), net);

    let interfaces = vec![SpfInterface {
        address: Ipv4Addr::new(172, 30, 0, 2),
        mask: Ipv4Addr::new(255, 255, 255, 0),
        sw_if_index: 1, // 'wan'
        cost: 10,
    }];

    let neighbors = vec![SpfNeighbor {
        router_id: Ipv4Addr::new(172, 30, 0, 1),
        address: Ipv4Addr::new(172, 30, 0, 1),
        sw_if_index: 1,
    }];

    let routes = calculate_spf(
        Ipv4Addr::new(172, 30, 0, 2),
        &lsdb,
        &interfaces,
        &neighbors,
    );

    // We should have a route to 10.99.0.1/32 with the correct next-hop
    let r = routes
        .iter()
        .find(|r| r.prefix == Ipv4Addr::new(10, 99, 0, 1))
        .expect("missing route to 10.99.0.1/32");

    assert_eq!(
        r.next_hop,
        Ipv4Addr::new(172, 30, 0, 1),
        "next-hop must be the remote router's address on the transit network"
    );
    assert_eq!(
        r.sw_if_index, 1,
        "outgoing interface must be our wan sw_if_index"
    );
    // Cost = our transit metric (10) + R2's stub metric (0) = 10
    assert_eq!(r.cost, 10);
}

// ============================================================================
// Group 7: Inter-area routing (RFC 2328 Section 16.2)
// ============================================================================

/// Test INTERAREA.1: Type 3 Summary-LSA encoding round-trip.
///
/// Purpose: Verify that Summary-LSA bodies serialize and parse correctly,
/// including the 24-bit metric field that has 8 reserved bits in front.
///
/// References: RFC 2328 Section A.4.4
#[test]
fn interarea_1_summary_lsa_roundtrip() {
    // Build a Type 3 LSA for 10.50.0.0/24 with metric 100, advertised by ABR 1.1.1.1
    let lsa = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::SummaryNetwork,
            link_state_id: Ipv4Addr::new(10, 50, 0, 0),
            advertising_router: Ipv4Addr::new(1, 1, 1, 1),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 28, // 20-byte header + 8-byte body
        },
        body: LsaBody::Summary(SummaryLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            metric: 100,
        }),
    };

    let encoded = lsa.encode();
    assert_eq!(encoded.len(), 28);

    let parsed = Lsa::parse(&encoded).expect("parse summary LSA");
    assert_eq!(parsed.header.ls_type, LsaType::SummaryNetwork);
    assert_eq!(parsed.header.link_state_id, Ipv4Addr::new(10, 50, 0, 0));
    assert_eq!(
        parsed.header.advertising_router,
        Ipv4Addr::new(1, 1, 1, 1)
    );

    match parsed.body {
        LsaBody::Summary(s) => {
            assert_eq!(s.network_mask, Ipv4Addr::new(255, 255, 255, 0));
            assert_eq!(s.metric, 100);
        }
        _ => panic!("expected Summary body"),
    }
}

/// Test INTERAREA.2: Inter-area route from a Type 3 Summary-LSA.
///
/// Purpose: Verify that when an ABR advertises a Type 3 LSA into our area,
/// SPF computes an inter-area route with cost = (cost-to-ABR) + (Type 3 metric)
/// and the next-hop inherited from the path to the ABR.
///
/// Topology:
///   us (R1, 1.1.1.1) -- broadcast net -- ABR (R2, 2.2.2.2 / DR)
///   ABR advertises Type 3 LSA for 10.50.0.0/24 with metric 100
///   Cost from us to ABR = 10 (transit network cost)
///   Expected inter-area route: 10.50.0.0/24 via 172.30.0.2 cost=110
///
/// References: RFC 2328 Section 16.2
#[test]
fn interarea_2_route_via_summary_lsa() {
    let mut lsdb = HashMap::new();

    // Our Router-LSA
    let r1 = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Router,
            link_state_id: Ipv4Addr::new(1, 1, 1, 1),
            advertising_router: Ipv4Addr::new(1, 1, 1, 1),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36,
        },
        body: LsaBody::Router(RouterLsa {
            flags: 0,
            links: vec![RouterLink {
                link_id: Ipv4Addr::new(172, 30, 0, 2), // DR
                link_data: Ipv4Addr::new(172, 30, 0, 1), // us
                link_type: RouterLinkType::TransitNetwork,
                num_tos: 0,
                metric: 10,
            }],
        }),
    };
    lsdb.insert(r1.key(), r1);

    // ABR's Router-LSA (with B flag)
    let r2 = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Router,
            link_state_id: Ipv4Addr::new(2, 2, 2, 2),
            advertising_router: Ipv4Addr::new(2, 2, 2, 2),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36,
        },
        body: LsaBody::Router(RouterLsa {
            flags: RouterLsa::B_FLAG,
            links: vec![RouterLink {
                link_id: Ipv4Addr::new(172, 30, 0, 2),
                link_data: Ipv4Addr::new(172, 30, 0, 2),
                link_type: RouterLinkType::TransitNetwork,
                num_tos: 0,
                metric: 10,
            }],
        }),
    };
    lsdb.insert(r2.key(), r2);

    // Network-LSA originated by ABR (DR)
    let net = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::Network,
            link_state_id: Ipv4Addr::new(172, 30, 0, 2),
            advertising_router: Ipv4Addr::new(2, 2, 2, 2),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 32,
        },
        body: LsaBody::Network(NetworkLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            attached_routers: vec![
                Ipv4Addr::new(1, 1, 1, 1),
                Ipv4Addr::new(2, 2, 2, 2),
            ],
        }),
    };
    lsdb.insert(net.key(), net);

    // Type 3 Summary-LSA from ABR for 10.50.0.0/24 with metric 100
    let summary = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::SummaryNetwork,
            link_state_id: Ipv4Addr::new(10, 50, 0, 0),
            advertising_router: Ipv4Addr::new(2, 2, 2, 2),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 28,
        },
        body: LsaBody::Summary(SummaryLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            metric: 100,
        }),
    };
    lsdb.insert(summary.key(), summary);

    let interfaces = vec![SpfInterface {
        address: Ipv4Addr::new(172, 30, 0, 1),
        mask: Ipv4Addr::new(255, 255, 255, 0),
        sw_if_index: 1,
        cost: 10,
    }];
    let neighbors = vec![SpfNeighbor {
        router_id: Ipv4Addr::new(2, 2, 2, 2),
        address: Ipv4Addr::new(172, 30, 0, 2),
        sw_if_index: 1,
    }];

    // Run SPF and capture router paths for inter-area calc
    let (_intra, paths) = calculate_spf_with_paths(
        Ipv4Addr::new(1, 1, 1, 1),
        &lsdb,
        &interfaces,
        &neighbors,
    );

    let inter = calculate_inter_area_routes(&lsdb, &paths);

    let r = inter
        .iter()
        .find(|r| r.prefix == Ipv4Addr::new(10, 50, 0, 0))
        .expect("inter-area route to 10.50.0.0/24");

    assert_eq!(r.prefix_len, 24);
    assert_eq!(
        r.next_hop,
        Ipv4Addr::new(172, 30, 0, 2),
        "next-hop should be the ABR"
    );
    assert_eq!(r.sw_if_index, 1);
    assert_eq!(r.cost, 110, "cost-to-ABR (10) + Type 3 metric (100)");
}

// ============================================================================
// Group 8: Stub area behavior (RFC 2328 Section 3.6)
// ============================================================================

/// Test STUB.1: Area::accepts_as_external() semantics.
///
/// Purpose: Verify that only Normal areas accept Type 5 LSAs; Stub and
/// NSSA areas reject them.
///
/// References: RFC 2328 Section 3.6
#[test]
fn stub_1_accepts_as_external() {
    use ospfd::area::{Area, AreaType};
    let router_id = Ipv4Addr::new(1, 1, 1, 1);

    let normal = Area::new(Ipv4Addr::UNSPECIFIED, AreaType::Normal, router_id);
    assert!(normal.accepts_as_external());

    let stub = Area::new(Ipv4Addr::new(0, 0, 0, 1), AreaType::Stub, router_id);
    assert!(!stub.accepts_as_external());

    let nssa = Area::new(Ipv4Addr::new(0, 0, 0, 2), AreaType::Nssa, router_id);
    assert!(!nssa.accepts_as_external());
}

/// Test STUB.2: Default-route Summary-LSA can be originated into a stub.
///
/// Purpose: Verify the wire format and semantics of a default Type 3
/// LSA. The ABR must originate a Type 3 with network_mask=0.0.0.0 and
/// link_state_id=0.0.0.0, advertising the area's default_cost metric,
/// so internal stub routers can reach external destinations.
///
/// References: RFC 2328 Section 12.4.3 ("Stub area support")
#[test]
fn stub_2_default_summary_lsa_roundtrip() {
    let router_id = Ipv4Addr::new(1, 1, 1, 1);
    let lsa = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::SummaryNetwork,
            link_state_id: Ipv4Addr::UNSPECIFIED,
            advertising_router: router_id,
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 28,
        },
        body: LsaBody::Summary(SummaryLsa {
            network_mask: Ipv4Addr::UNSPECIFIED,
            metric: 10, // configured default_cost
        }),
    };

    let encoded = lsa.encode();
    let parsed = Lsa::parse(&encoded).expect("parse default summary");

    assert_eq!(parsed.header.ls_type, LsaType::SummaryNetwork);
    assert_eq!(parsed.header.link_state_id, Ipv4Addr::UNSPECIFIED);
    assert_eq!(parsed.header.advertising_router, router_id);

    match parsed.body {
        LsaBody::Summary(s) => {
            assert_eq!(s.network_mask, Ipv4Addr::UNSPECIFIED);
            assert_eq!(s.metric, 10);
        }
        _ => panic!("expected Summary body"),
    }
}

// ============================================================================
// Group 9: AS-External routing (RFC 2328 Section 16.4)
// ============================================================================

/// Test EXT.1: AS-External-LSA encoding round-trip.
///
/// Purpose: Verify that Type 5 AS-External LSAs serialize and parse correctly,
/// including the E bit for metric type and the 24-bit metric.
///
/// References: RFC 2328 Section A.4.5
#[test]
fn ext_1_as_external_lsa_roundtrip() {
    let lsa = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::AsExternal,
            link_state_id: Ipv4Addr::new(192, 0, 2, 0),
            advertising_router: Ipv4Addr::new(1, 1, 1, 1),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36, // 20-byte header + 16-byte body
        },
        body: LsaBody::AsExternal(AsExternalLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            metric_type_2: true,
            metric: 20,
            forwarding_address: Ipv4Addr::UNSPECIFIED,
            external_route_tag: 0xdeadbeef,
        }),
    };

    let encoded = lsa.encode();
    assert_eq!(encoded.len(), 36);

    let parsed = Lsa::parse(&encoded).expect("parse AS-External");
    assert_eq!(parsed.header.ls_type, LsaType::AsExternal);

    match parsed.body {
        LsaBody::AsExternal(e) => {
            assert_eq!(e.network_mask, Ipv4Addr::new(255, 255, 255, 0));
            assert!(e.metric_type_2, "E bit set");
            assert_eq!(e.metric, 20);
            assert_eq!(e.forwarding_address, Ipv4Addr::UNSPECIFIED);
            assert_eq!(e.external_route_tag, 0xdeadbeef);
        }
        _ => panic!("expected AsExternal body"),
    }
}

/// Test EXT.2: Type 2 external route (only metric counts).
///
/// Purpose: Verify that a Type 2 AS-External LSA computes its route cost
/// using the advertised metric only, ignoring the internal cost-to-ASBR.
///
/// References: RFC 2328 Section 16.4
#[test]
fn ext_2_type2_metric_ignores_asbr_cost() {
    let mut as_external = HashMap::new();
    let ext_lsa = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::AsExternal,
            link_state_id: Ipv4Addr::new(10, 10, 10, 0),
            advertising_router: Ipv4Addr::new(9, 9, 9, 9),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36,
        },
        body: LsaBody::AsExternal(AsExternalLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            metric_type_2: true, // Type 2
            metric: 42,
            forwarding_address: Ipv4Addr::UNSPECIFIED,
            external_route_tag: 0,
        }),
    };
    as_external.insert(ext_lsa.key(), ext_lsa);

    // Pretend the ASBR is reachable via cost 1000
    let mut router_paths = HashMap::new();
    router_paths.insert(
        Ipv4Addr::new(9, 9, 9, 9),
        (
            1000,
            ospfd::proto::spf::NextHop {
                address: Ipv4Addr::new(172, 30, 0, 1),
                sw_if_index: 5,
            },
        ),
    );

    let routes = calculate_external_routes(&as_external, &router_paths);
    let r = routes
        .iter()
        .find(|r| r.prefix == Ipv4Addr::new(10, 10, 10, 0))
        .expect("external route");

    // Type 2: cost should be exactly the external metric (42), not 1000+42
    assert_eq!(r.cost, 42);
    assert_eq!(r.next_hop, Ipv4Addr::new(172, 30, 0, 1));
    assert_eq!(r.sw_if_index, 5);
}

/// Test EXT.3: Type 1 external route (cost sums with ASBR cost).
#[test]
fn ext_3_type1_metric_sums_with_asbr_cost() {
    let mut as_external = HashMap::new();
    let ext_lsa = Lsa {
        header: LsaHeader {
            ls_age: 0,
            options: 0x02,
            ls_type: LsaType::AsExternal,
            link_state_id: Ipv4Addr::new(10, 10, 10, 0),
            advertising_router: Ipv4Addr::new(9, 9, 9, 9),
            ls_sequence_number: INITIAL_SEQUENCE_NUMBER,
            ls_checksum: 0,
            length: 36,
        },
        body: LsaBody::AsExternal(AsExternalLsa {
            network_mask: Ipv4Addr::new(255, 255, 255, 0),
            metric_type_2: false, // Type 1
            metric: 42,
            forwarding_address: Ipv4Addr::UNSPECIFIED,
            external_route_tag: 0,
        }),
    };
    as_external.insert(ext_lsa.key(), ext_lsa);

    let mut router_paths = HashMap::new();
    router_paths.insert(
        Ipv4Addr::new(9, 9, 9, 9),
        (
            1000,
            ospfd::proto::spf::NextHop {
                address: Ipv4Addr::new(172, 30, 0, 1),
                sw_if_index: 5,
            },
        ),
    );

    let routes = calculate_external_routes(&as_external, &router_paths);
    let r = routes
        .iter()
        .find(|r| r.prefix == Ipv4Addr::new(10, 10, 10, 0))
        .expect("external route");

    // Type 1: cost should be 1000 + 42 = 1042
    assert_eq!(r.cost, 1042);
}

/// Test LSA.2: LSA header freshness comparison.
///
/// Purpose: Verify that `is_more_recent_than` correctly implements the
/// RFC 2328 Section 13.1 LSA comparison rules: higher sequence number wins,
/// then higher checksum, then age rules.
#[test]
fn lsa_2_freshness_comparison() {
    let h1 = LsaHeader {
        ls_age: 100,
        options: 0x02,
        ls_type: LsaType::Router,
        link_state_id: Ipv4Addr::new(1, 1, 1, 1),
        advertising_router: Ipv4Addr::new(1, 1, 1, 1),
        ls_sequence_number: 0x80000001u32 as i32,
        ls_checksum: 0,
        length: 36,
    };

    // Higher sequence number is more recent
    let mut h2 = h1.clone();
    h2.ls_sequence_number = 0x80000002u32 as i32;
    assert_eq!(
        h2.is_more_recent_than(&h1),
        std::cmp::Ordering::Greater,
        "higher sequence wins"
    );
    assert_eq!(
        h1.is_more_recent_than(&h2),
        std::cmp::Ordering::Less,
        "lower sequence loses"
    );

    // MaxAge LSA is more recent than non-MaxAge at same sequence
    let mut h3 = h1.clone();
    h3.ls_age = MAX_AGE;
    assert_eq!(
        h3.is_more_recent_than(&h1),
        std::cmp::Ordering::Greater,
        "MaxAge is more recent"
    );
}

/// Test NBMA.1: Non-Broadcast interface runs the Broadcast DR-election FSM.
///
/// Purpose: Verify that a router on an NBMA interface enters Waiting on
/// InterfaceUp (just like Broadcast), runs DR election on WaitTimer, and
/// — alone on the segment — becomes DR.
///
/// References: RFC 2328 §A.4.5 (non-broadcast networks use broadcast ISM)
#[test]
fn nbma_1_interface_runs_broadcast_fsm() {
    let mut iface = OspfInterface::new(
        "wan".to_string(),
        1,
        Ipv4Addr::new(10, 0, 0, 1),
        Ipv4Addr::new(255, 255, 255, 0),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::NonBroadcast,
        Ipv4Addr::new(10, 0, 0, 1),
    );
    iface.priority = 1;
    iface.static_neighbors.push(StaticNeighbor {
        address: Ipv4Addr::new(10, 0, 0, 2),
        priority: 1,
    });

    // Must enter Waiting (not go straight to DROther or P2P)
    iface.handle_event(&InterfaceEvent::InterfaceUp);
    assert_eq!(iface.state, InterfaceState::Waiting);
    assert!(iface.wait_timer_expiry.is_some());

    // Wait timer fires: alone, so we become DR
    iface.handle_event(&InterfaceEvent::WaitTimer);
    assert_eq!(iface.state, InterfaceState::DR);
    assert_eq!(iface.dr, Ipv4Addr::new(10, 0, 0, 1));
}

/// Test NBMA.2: NBMA static neighbor list survives construction.
///
/// Regression guard: `OspfInterface::new` historically default-initialised
/// `static_neighbors` to `Vec::new()`. Confirm that appending static
/// neighbors doesn't get lost across the state machine.
#[test]
fn nbma_2_static_neighbors_preserved_across_fsm() {
    let mut iface = OspfInterface::new(
        "wan".to_string(),
        1,
        Ipv4Addr::new(10, 0, 0, 1),
        Ipv4Addr::new(255, 255, 255, 0),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::NonBroadcast,
        Ipv4Addr::new(10, 0, 0, 1),
    );
    iface.static_neighbors.push(StaticNeighbor {
        address: Ipv4Addr::new(10, 0, 0, 2),
        priority: 1,
    });
    iface.static_neighbors.push(StaticNeighbor {
        address: Ipv4Addr::new(10, 0, 0, 3),
        priority: 0,
    });

    iface.handle_event(&InterfaceEvent::InterfaceUp);
    iface.handle_event(&InterfaceEvent::WaitTimer);

    assert_eq!(iface.static_neighbors.len(), 2);
    assert_eq!(iface.static_neighbors[0].address, Ipv4Addr::new(10, 0, 0, 2));
    assert_eq!(iface.static_neighbors[1].priority, 0);
}

/// Test NBMA.3: `should_form_adjacency` returns true for NBMA when DR/BDR.
///
/// NBMA shares the broadcast adjacency rule: only DR and BDR form full
/// adjacencies with DROther neighbors; two DROthers stop at 2-Way.
#[test]
fn nbma_3_adjacency_rule_matches_broadcast() {
    let mut iface = OspfInterface::new(
        "wan".to_string(),
        1,
        Ipv4Addr::new(10, 0, 0, 1),
        Ipv4Addr::new(255, 255, 255, 0),
        Ipv4Addr::UNSPECIFIED,
        NetworkType::NonBroadcast,
        Ipv4Addr::new(10, 0, 0, 1),
    );
    iface.state = InterfaceState::DR;
    iface.dr = Ipv4Addr::new(10, 0, 0, 1);

    let n = Neighbor::new(Ipv4Addr::new(2, 2, 2, 2), Ipv4Addr::new(10, 0, 0, 2));
    // We're DR, so we form adjacency with everyone in >=2-Way
    assert!(iface.should_form_adjacency(&n));

    // A DROther on a broadcast-style segment would not form adjacency
    // with another DROther.
    iface.state = InterfaceState::DROther;
    iface.dr = Ipv4Addr::new(10, 0, 0, 99);
    iface.bdr = Ipv4Addr::new(10, 0, 0, 98);
    let n2 = Neighbor::new(Ipv4Addr::new(3, 3, 3, 3), Ipv4Addr::new(10, 0, 0, 3));
    assert!(!iface.should_form_adjacency(&n2));
}
